### ISSUE TITLE
Not able reproduce the .pkl files as in the already given .pkl file

### ISSUE THREAD

**Issue by srishastry123** [sandberg-lab/aRME_and_bursting#2]
I am trying to reproduce the data file .pkl using below command when I compare output which is already given and self generated .pkl files which are not matching can you please guide me what went wrong 

command what I have tried 
`./txburstML.py data/nature_paper/SS3_cast_UMIs_mESC.csv`

output from  my run  mentioned as test
https://github.com/srishastry123/new.git

I have tried same dependency version and updated both gave same result please help me 

Thank you

**Comment by AntonJMLarsson** [comment]
This looks like the same question you asked in the txburst repo. Please refrain from posting duplicate question across multiple repos. If this is not the case let me know.

Best,
Anton
